# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbbdd5868f6d9764fc4846b1fb0fb9fa92438df4d9a7841e838ec4e5bfb8df2e9006b4e158e4b0f5768ef0129e43afc690d4ae8499716b508485832fcfd24a85

test:
  secret_key_base: c9b9f956558276a5933e2bbba3626fbf0947b52ff6fe69eb3911626fa66ad48286dc7f0fb725c17490031d3611707ff4b14c019ba01c348338fd9706a4228dcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
